### ISSUE TITLE
File access control still active after deinstalling

### ISSUE THREAD

**Issue by Jebop** [nextcloud/files_accesscontrol#209] opened 2021-08-18 09:16 UTC
Just to try how the app behaves I recently set up a flow as follows, 

if > file is accessed
and > filename is (example.pdf)
and > User is part of Group (xyz) 
then > block file access 

after I had done my testing, I removed the entire app from my Nextcloud without deleting the previously mentioned flow thinking that by removing the app this would also delete the Flow.

After removing, the access control did disappear from the Flow menu, but it seems as if the access control is still active.
Users from the Group still can't access the files!

I thought by reinstalling the flow might reappear in the Flow menu but that didn't happen.

Is there a way to remove this manually from the Server?

### Server configuration

**Operating system**: Linux 4.15.0 x86_64

**Nextcloud version:** 20.0.8

**Comment by CarlSchwan** [comment] 2021-09-29 16:29
Hi, I couldn't reproduce. Could you please give me the output of the following SQL command `select * from oc_flow_checks; select * from oc_flow_operations_scope; select * from oc_flow_operations;`?

**Comment by Jebop** [comment] 2021-09-30 07:24
Unfortunately not... my Server got Hacked and my Nextcloud is gone :(

**Comment by blizzz** [comment] 2022-08-18 10:59
closing as not reproducible.

**Closed by blizzz** 2022-08-18 10:59 UTC
