### ISSUE TITLE
Inconsitent handling of shared folders that is inaccessible

### ISSUE THREAD

**Issue by mickenordin** [nextcloud/files_accesscontrol#588] opened 2024-08-30 14:30 UTC
This is similar to #97 but I think behaviour has changed enough to warrant a new report.
### Steps to reproduce
1. Create a tag
2. Create a flow that denies access to the tag (but perhaps not to yourself)
3. Create a folder with said tag
4. Share the folder with someone

### Expected behaviour
Folder is never visible anywhere OR folder is visible and greyed out (and a limited details view is accessible). I think I prefer the latter solution, because then at least user can get some indication that there is some access issue. Having the folder there, but greyed out would solve any other issues with confused clients as well.

### Actual behaviour
Folder is visible in dashboard and in "shares" meny in files app, but not visible in the list in the files app

### Server configuration
Nextcloud 29 with files_accesscontrol

Below are screenshots from this scenario where ''Admin" shares a folder with "Ordinary User":
### Create folder with tag and share it
![2024-08-30T16:15:43,925091604+02:00](https://github.com/user-attachments/assets/b1852f24-a938-4cae-85f9-48ddb25505d2)
### Create flow to block
![2024-08-30T16:16:36,650880916+02:00](https://github.com/user-attachments/assets/ead11dd1-c8b4-461d-b932-c345841a9433)
### User logs in and sees folder
![2024-08-30T16:12:07,451974240+02:00](https://github.com/user-attachments/assets/d57c5a5c-ad29-4e56-8ce0-00bc61761e9a)
### User sees folder in overview but not list
![2024-08-30T16:11:47,351516017+02:00](https://github.com/user-attachments/assets/5c5461df-0b25-4330-b319-3dd805b87654)
### User sees folder in shares, but cannot access details
![2024-08-30T16:11:23,402776230+02:00](https://github.com/user-attachments/assets/34391283-412c-40d7-bd30-5a2be6cbffe5)

**Comment by nickvergessen** [comment] 2024-09-09 11:02
Duplicate of https://github.com/nextcloud/files_accesscontrol/issues/544
Most important details in https://github.com/nextcloud/files_accesscontrol/issues/544#issuecomment-2296603976

**Closed by nickvergessen** 2024-09-09 11:02 UTC
