### ISSUE TITLE
Flow broken after upgrade from Nextcloud 21.03 to 22.2.3

### ISSUE THREAD

**Issue by Max-hm** [nextcloud/files_accesscontrol#221] opened 2021-11-19 10:50 UTC
### Steps to reproduce
1. Access Nextcloud instance and navigate to Settings > Flow

### Expected behaviour
Tell us what should happen

Access Flow Controls for File Access Permissions

### Actual behaviour
Tell us what happens instead

Error message is displayed 
Internal Server Error
The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.

### Server configuration

**Operating system**: Centos

**Web server:** Apache

**Database:** MariaDB 10.03

**PHP version:** 7.3

**Nextcloud version:**  22.2.3

**Where did you install Nextcloud from:** Official repository

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No

### Client configuration
Chrome 96.0.4664.45
Firefox 94.0 (64-bit)

**Operating system:**
Ubuntu 20.04 LTS

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

**Comment by caco3** [comment] 2022-03-19 22:05
You are not really giving enough information, so its hard to understand what your exact problem is.
I had a similar problem and it was caused by a change of the file owner. before it was `root`, now its user `33`.
Maybe this helps.

See https://github.com/nextcloud/files_accesscontrol/issues/232

**Comment by blizzz** [comment] 2022-08-18 10:55
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.

**Closed by blizzz** 2022-08-18 10:55 UTC
