### ISSUE TITLE
file access was broken

### ISSUE THREAD

**Issue by rendxq** [nextcloud/files_accesscontrol#69] opened 2017-06-28 15:32 UTC
### Steps to reproduce
1. assigning  tag "tag1" to file
2. create rule with tag1

### Expected behaviour
I expect to see files/folders exclude tagged tag1 file

### Actual behaviour
1. I cannot access to any files.. see nothing.
2. Security & setup warnings show me error: Your web server is not yet set up properly to allow file synchronization because the WebDAV interface seems to be broken.
### Server configuration

This is NextCloud VM from here https://cloud.techandme.se/index.php/s/lTjoMr5smSYHIiM  (Nextcloud 12 + files_accesscontrop app )

**Comment by nickvergessen** [comment] 2017-06-28 20:45
Duplicate of #65

**Closed by nickvergessen** 2017-06-28 20:45 UTC
