### ISSUE TITLE
continue" targeting switch is equivalent to "break"

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/files_accesscontrol#153] opened 2020-02-16 15:55 UTC
I use nextcloud 18.0.1 with calendar synchronization but lately my server goes downtime. registering error:

continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? at /var/www/Franco/nx/apps/workflowengine/lib/Helper/LogContext.php#55

I have disabled app file access control. but how to solve?

I have php 7.3 and apache 2.4.41 nextcloud 18.0.1 and raspbian server

**Comment by nickvergessen** [comment] 2020-02-16 16:13
Duplicate of https://github.com/nextcloud/server/issues/19504

**Closed by nickvergessen** 2020-02-16 16:13 UTC
