### ISSUE TITLE
Deny sync for Desktop Client on GroupFolder

### ISSUE THREAD

**Issue by patricksebastien** [nextcloud/files_accesscontrol#197] opened 2021-04-21 02:06 UTC
Here's my setup (NC and app stable all updated):
![image](https://user-images.githubusercontent.com/441764/115486343-82af9700-a224-11eb-9821-a1d87616ee05.png)

The groupfolder have the tag: Internal, but the desktop client is still listing the folder when clicking **Choose what to sync**. How to fix this?

**Comment by blizzz** [comment] 2021-04-21 10:18
Duplicate of https://github.com/nextcloud/files_accesscontrol/issues/97

**Closed by blizzz** 2021-04-21 10:18 UTC
