### ISSUE TITLE
Denied files and folders are hard to distinguish

### ISSUE THREAD

**Issue by ManfredWisniewski** [nextcloud/files_accesscontrol#587] opened 2024-08-27 08:05 UTC
### Steps to reproduce
1. Deny some files
2. Use the account to which access has been denied
3. try to distinguish the access without the mouse cursor

### Expected behaviour
Add a .css class or tag to the row so that how denied files are displayed to the user can be handled via individual css of the nextcloud installation.

`<td class="files-list__row-checkbox access-denied"></td>`

### Actual behaviour
There is no way to distinguish between normal and denied files or folders via the markup.
`<td class="files-list__row-checkbox"></td>`

![image](https://github.com/user-attachments/assets/f3dd8c32-0925-41dc-b874-260a65478482)
The user has access to files and folders with the tag SK1 but not SK3

**Comment by nickvergessen** [comment] 2024-08-27 08:07
Duplicate of https://github.com/nextcloud/files_accesscontrol/issues/544

**Closed by nickvergessen** 2024-08-27 08:07 UTC
